actions:
  COMBO:
    - ['press', 'shift']
    - ['press', 'w']
    - ['delay', 0.5]
    - ['release', 'w']
    - ['release', 'shift']
    - ['press_mouse', 'left']
    - ['move_mouse', 10, 0, 2]
    - ['release_mouse', 'left']
    - ['delay', 0.5]
  MOVE_AND_ATTACK:
    - ['press_mouse', 'left']
    - ['move_mouse', 5, 0, 2]
    - ['release_mouse', 'left']
    - ['delay', 0.5]
  MOUSE_TEST:
    - ['delay', 1]
    - ['move_mouse', 200, 0, 2]
    - ['delay', 0.5]
  RECOVER:
    - ['press', 'r']
    - ['delay', 0.02]
    - ['release', 'r']


hot_list:
  - MOUSE_TEST
  - RECOVER
  - MOVE_AND_ATTACK
