actions:

  IDLE:
    - ['delay', 1.0 ]

  LIGHT_ATTACK:
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
  
  HEAVY_ATTACK:
    - ['press_mouse', 'right']
    - ['delay', 0.15]
    - ['release_mouse', 'right']
    - ['delay', 2.53]
  
  DRINK_POTION:
    - ['press', 'r']
    - ['delay', 0.12]
    - ['release', 'r']
    - ['delay', 1.37]
  
  DODGE:
    - ['press', 'space']
    - ['delay', 0.16]
    - ['release', 'space']
    - ['delay', 0.34]

  ATTACK_DODGE:
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
    - ['press', 'space']
    - ['delay', 0.16]
    - ['release', 'space']
    - ['delay', 0.34]  
  
  QIESHOU:
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.25]
    - ['press_mouse', 'right']
    - ['delay', 0.15]
    - ['release_mouse', 'right']
    - ['delay', 0.96]

  FIVE_HIT_COMBO:
    - ['press_mouse', 'left']
    - ['delay', 0.13 ]
    - ['release_mouse', 'left']
    - ['delay', 0.39]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 0.62]
    - ['press_mouse', 'left']
    - ['delay', 0.17 ]
    - ['release_mouse', 'left']
    - ['delay', 0.73]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 1]
    - ['press_mouse', 'left']
    - ['delay', 0.14 ]
    - ['release_mouse', 'left']
    - ['delay', 1]

  SKILL_1: &SKILL_1
    - ['press', '1']
    - ['delay', 0.14]
    - ['release', '1']
    - ['delay', 0.3]
  
  SKILL_2: &SKILL_2
    - ['press', '2']
    - ['delay', 0.14]
    - ['release', '2']
    - ['delay', 0.3]
  
  SKILL_3: &SKILL_3
    - ['press', '3']
    - ['delay', 0.14]
    - ['release', '3']
    - ['delay', 1.96]
  
  SKILL_4: &SKILL_4
    - ['press', '4']
    - ['delay', 0.14]
    - ['release', '4']
    - ['delay', 1.19]

  STEALTH_CHARGE:
    - *SKILL_2
    - ['press_mouse', 'right']
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'd']
    - ['delay', 2.45]
    - ['release', 'd']
    - ['press', 'w']
    - ['delay', 1.45]
    - ['release', 'w']
    - ['press', 'a']
    - ['delay', 1.45]
    - ['release', 'a']
    - ['press', 'w']
    - ['delay', 0.45]
    - ['release', 'w']
    - ['delay', 0.2]
    - ['release', 'shift']
    - ['release_mouse', 'right']
    - ['delay', 3.43]

  FABAO:
    - ['press', 't']
    - ['delay', 0.14]
    - ['release', 't']
    - ['delay', 1.19]
  
  TISHEN:
    - ['press', 'f']
    - ['delay', 0.14]
    - ['release', 'f']
    - ['delay', 4.15]

  MOVE_CAMERA_RIGHT:
    - ['move_mouse', 300, 0, 1]
    - ['delay', 1]

  MOVE_CAMERA_LEFT:
    - ['move_mouse', -300, 0, 1]
    - ['delay', 1]

  RUN_FORWARD: &RUN_FORWARD
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'w']
    - ['delay', 2]
    - ['release', 'w']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_BACKWARD: &RUN_BACKWARD
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 's']
    - ['delay', 2]
    - ['release', 's']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_LEFT: &RUN_LEFT
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'a']
    - ['delay', 2]
    - ['release', 'a']
    - ['delay', 0.2]
    - ['release', 'shift']

  RUN_RIGHT: &RUN_RIGHT
    - ['press', 'shift']
    - ['delay', 0.2]
    - ['press', 'd']
    - ['delay', 2]
    - ['release', 'd']
    - ['delay', 0.2]
    - ['release', 'shift']

hot_list:
  - STEALTH_CHARGE
  - LIGHT_ATTACK
  - HEAVY_ATTACK
  - DRINK_POTION
  - DODGE
  - ATTACK_DODGE
  - QIESHOU
  - FIVE_HIT_COMBO
  - SKILL_1
  - STEALTH_CHARGE
  - SKILL_3
  - FABAO
  - TISHEN

